name: Fetch Commits from Branch

on:
  workflow_dispatch:
 # workflow_run:
  #  workflows: ["fetch-commits"]  # Replace with the name of the workflow that triggers this action

jobs:
  fetch-commits:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Fetch Commits
      run: |
        # Set your GitHub token
        # TOKEN=$PAT_TOKEN
        
        # Define the branch and repository
        BRANCH="dev"  # Replace with your desired branch name
        REPO="anujnarayan23/Automation_GitHub_Actions.git"  # Replace with your repository
        
        # Fetch commit IDs from the branch
        COMMITS=$(curl -s -H "Authorization: token $PAT_TOKEN" "https://api.github.com/repos/${{ github.repository }}/commits?sha=$BRANCH" | jq -r '.[].sha')
        
        echo "Commit IDs from branch $BRANCH:"
        echo "$COMMITS"
        
        # You can use the $COMMITS variable in your workflow as needed  
      env:
        PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
