name: Manual Branch Deletion

on:
  workflow_dispatch:
    inputs:
      pr_number:
        description: 'Pull Request Number'
        required: true

jobs:
  delete-branch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Delete branch
        run: |
          git ls-remote --heads origin
          PR_NUMBER="${{ github.event.inputs.pr_number }}"
          BRANCH="pr-$PR_NUMBER"
          echo "Deleting branch: $BRANCH"
          git push origin --delete "$BRANCH"
        shell: bash
