name: Delete Branches Manually

on:
  workflow_dispatch:
    inputs:
      branch_names:
        description: 'Comma-separated list of branch names to delete'
        required: true

jobs:
  delete_branches:
    runs-on: ubuntu-latest

    steps:
    - name: Check Input and Split Branch Names
      id: split_branches
      run: |
        IFS=',' read -ra branches <<< "$INPUT_BRANCH_NAMES"
        for branch in "${branches[@]}"; do
          echo "Deleting branch: $branch"
          git push origin --delete "$branch"
        done
      env:
        INPUT_BRANCH_NAMES: ${{ github.event.inputs.branch_names }}
