name: Manual Branch Deletion

on:
  workflow_dispatch:
    inputs:
      branch_name:
        description: 'Provide the branch name'
        required: true

jobs:
  delete-branch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Delete branch
        run: |
          git ls-remote --heads origin
          #PR_NUMBER="${{ github.event.inputs.pr_number }}"
          #BRANCH="pr-$PR_NUMBER"
          echo "Deleting branch: ${{ github.event.inputs.branch_name }}"
          git push origin --delete "${{ github.event.inputs.branch_name }}"
        shell: bash
