name: Cherry-Pick and Merge

on:
  workflow_dispatch:
    inputs:
      commit_ids:
        description: 'Comma-separated list of commit IDs to cherry-pick and merge'
        required: true

jobs:
  cherry_pick_and_merge:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Check Input and Split Commit IDs
      id: split_commits
      run: |
        IFS=',' read -ra commits <<< "$INPUT_COMMIT_IDS"
        for commit in "${commits[@]}"; do
          echo "Cherry-picking commit: $commit"
          git cherry-pick $commit
          if [ $? -ne 0 ]; then
            echo "Cherry-pick failed for commit: $commit"
            exit 1
          fi
        done
      env:
        INPUT_COMMIT_IDS: ${{ github.event.inputs.commit_ids }}

    - name: Commit Cherry-Picked Changes
      run: |
        git config --global user.name "Anuj Narayan"
        git config --global user.email "anujnarayan11@gmail.com"
        git commit -am "Cherry-picked changes"
      if: steps.split_commits.outputs

    - name: Create Feature Branch
      run: |
        git checkout -b feature-branch test
        git push origin feature-branch
      if: success() && steps.split_commits.outputs

    - name: Create Pull Request
      id: create_pr
      uses: actions/checkout@v2
      with:
        ref: "feature-branch"
      if: success() && steps.split_commits.outputs

    - name: Merge Pull Request
      run: |
        pr_url="$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/pull/${{ steps.create_pr.outputs.pull_request }}"
        echo "Opening PR at $pr_url"
      if: success() && steps.create_pr.outputs

    - name: Close Workflow on Conflict
      run: |
        echo "Conflicts detected in the pull request. Resolve conflicts manually."
        exit 1
      if: failure()
